### ISSUE TITLE
READMEs have wrong link to sys_log as part of the Installation instructions

### ISSUE THREAD

**Issue by MitchellGerdisch** [rightscale/rightscale-plugins#116]
### Plugin Name
Most if not all

### Issue Type
Documentation issue.
The Installation sections in the READMEs in the Azure and AWS plugins and possibly others link to where to find sys_log but the link is not correct.

### Plugin version
Current

### Scenario:
Just tryin' to follow the instructions.

### Steps to Reproduce:
Go to a plugin README and click on the sys_log link in the Installation steps.

### Expected Result:
Direct me to the where to find the sys_log package file.

### Actual Result:
404

**Comment by srpomeroy** [comment]
Tracked internally as PSASSET-797

**Comment by srpomeroy** [comment]
Fixed in #134
