### ISSUE TITLE
SQL Plugin: Storage Account key use

### ISSUE THREAD

**Issue by MitchellGerdisch** [rightscale/rightscale-plugins#25]
The SQL plugin security_policy resource (maybe others) requires knowing a Storage Account Access key and endpoint.
It would be nice if that info can be programmatically found.
For example, let me either create the storage account as part of the CAT that is using the plugin or identify a storage account by name to use and have the plugin get what it needs to be able to use the storage account.

**Comment by dfrankel33** [comment]
it might be of value to add a read-only Storage Account resource type to this plugin, to retrieve keys.  users would continue to create Storage Accounts via Placement Groups in RS, but we could then abstract the storageAccountAccessKey fields from the SQL resource declarations that use them.

**Comment by rshade** [comment]
there is now a resource for this: azure/rs_azure_storage
