### ISSUE TITLE
handle_retries is not defined 

### ISSUE THREAD

**Issue by MitchellGerdisch** [rightscale/rightscale-plugins#55]
The below line references a handle_retries definition that is not defined.
This throws an error when an error is encountered.
(I can do a PR if the intent was a simple try 3 times type of deal.)

https://github.com/rightscale/rightscale-plugins/blob/c02cffd4e5aa83cadcd9a2bf38a35727197ae80c/aws/rs_aws_rds/aws_rds_plugin.rb#L944

**Comment by rshade** [comment]
can you give it another go with latest?
